/****************
Generated by NODEBOOTSTRAPPER
Author: Ashutosh Kapoor
GIT LINK : https://github.com/ashu-kapoor/NODEBOOTSTRAPPER
****************/
const User = require("../models/User");
const bcrypt = require("bcrypt");
/**
 * @param {object} req - req object
 * @param {object} res - res object
 * @param {object} next - next object
 **/

module.exports.createUserController = (req, res, next) => {
  const username = req.body.username;
  const password = req.body.password;
  const role = req.body.role;
  const email = req.body.email;

  bcrypt
    .hash(password, process.env.passwordSalt)
    .then((hashPass) => {
      const user = new User({
        username,
        password: hashPass,
        role,
        email,
      });

      user
        .save()
        .then((result) => {
          console.log(result);
          res.status(201).json({
            id: result._id,
          });
        })
        .catch((err) => {
          throw err;
        });
    })
    .catch((err) => {
      if (!err.apiErrorCode) {
        err.apiErrorCode = 1000;
      }
      next(err);
    });
};
