/****************
Generated by NODEBOOTSTRAPPER
Author: Ashutosh Kapoor
GIT LINK : https://github.com/ashu-kapoor/NODEBOOTSTRAPPER
****************/
const Product = require("../models/Product");
/**
 * @param {object} req - req object
 * @param {object} res - res object
 * @param {object} next - next object
 **/

module.exports.createProductController = (req, res, next) => {
  const name = req.body.name;
  const code = req.body.code;
  const listPrice = req.body.listPrice;

  const product = new Product({
    name,
    code,
    listPrice,
  });

  product
    .save()
    .then((result) => {
      console.log(result);
      res.status(201).json({
        id: result._id,
      });
    })
    .catch((err) => {
      if (!err.apiErrorCode) {
        err.apiErrorCode = 1000;
      }
      next(err);
    });
};
