/****************
Generated by NODEBOOTSTRAPPER
Author: Ashutosh Kapoor
GIT LINK : https://github.com/ashu-kapoor/NODEBOOTSTRAPPER
****************/
const Contact = require("../models/Contact");
/**
 * @param {object} req - req object
 * @param {object} res - res object
 * @param {object} next - next object
 **/

module.exports.createContactController = (req, res, next) => {
  const name = req.body.name;
  const gender = req.body.gender;
  const title = req.body.title;
  const birthdate = req.body.birthdate;
  const department = req.body.department;
  const address = req.body.address;
  const phone = req.body.phone;
  const owner = req.body.owner;

  const contactObject = Object.assign(
    { name, gender, title, address, phone, owner },
    department === null ? null : { department },
    birthdate === null ? null : { birthdate: new Date(birthdate) }
  );

  const contact = new Contact({
    name,
    gender,
    title,
    birthdate,
    department,
    address,
    phone,
    owner,
  });

  contact
    .save()
    .then((result) => {
      console.log(result);
      res.status(201).json({
        id: result._id,
      });
    })
    .catch((err) => {
      if (!err.apiErrorCode) {
        err.apiErrorCode = 1000;
      }
      next(err);
    });
};
