/****************
Generated by NODEBOOTSTRAPPER
Author: Ashutosh Kapoor
GIT LINK : https://github.com/ashu-kapoor/NODEBOOTSTRAPPER
****************/
const User = require("../models/User");
const Opportunity = require("../models/Opportunity");
const Case = require("../models/Case");
const Contact = require("../models/Contact");
/**
 * @param {object} req - req object
 * @param {object} res - res object
 * @param {object} next - next object
 **/

module.exports.deleteUserController = (req, res, next) => {
  //Only delete user if not referenced anywhere
  const userId = req.params.userId;
  User.findById(userId)
    .then((user) => {
      if (!user) {
        const error = new Error();
        error.apiErrorCode = 7000;
        throw error;
      } else {
        //if user exists check it doesnt exist anywhere before deleting
        checkUserExists(user)
          .then((data) => {
            if (data) {
              //user is referenced
              const error = new Error();
              error.apiErrorCode = 1000;
              error.apiData = "User has records";
              throw error;
            } else {
              //user is not referenced
              user
                .delete()
                .then(() => {
                  res.status(204).send();
                })
                .catch((err) => {
                  throw err;
                });
            }
          })
          .catch((err) => {
            throw err;
          });
      }
    })
    .catch((err) => {
      if (!err.apiErrorCode) {
        err.apiErrorCode = 1000;
      }
      next(err);
    });
};

const checkUserExists = async function (user) {
  //Check user exists in Opty, Case, Contact if so resolev with true else false
  const optyCount = await Opportunity.countDocuments({ owner: user._id });
  const caseCount = await Case.countDocuments({ owner: user._id });
  const contactCount = await Contact.countDocuments({ owner: user._id });
  if (optyCount > 0 || caseCount > 0 || contactCount > 0) {
    return true;
  }
  return false;
};
