/****************
Generated by NODEBOOTSTRAPPER
Author: Ashutosh Kapoor
GIT LINK : https://github.com/ashu-kapoor/NODEBOOTSTRAPPER
****************/
const Contact = require("../models/Contact");

/**
 * @param {object} req - req object
 * @param {object} res - res object
 * @param {object} next - next object
 **/

module.exports.deleteContactController = (req, res, next) => {
  //Only delete user if not referenced anywhere
  const contactId = req.params.contactId;
  Contact.findById(contactId)
    .then((contact) => {
      if (!contact) {
        const error = new Error();
        error.apiErrorCode = 7000;
        throw error;
      } else {
        //if contact exists check it doesnt exist anywhere before deleting
        if (
          contact.cases.length > 0 ||
          contact.opportunities.length > 0 ||
          contact.attachments.length > 0
        ) {
          const error = new Error();
          error.apiErrorCode = 1000;
          error.apiData = "Contact has records";
          throw error;
        } else {
          contact
            .delete()
            .then(() => {
              res.status(204).send();
            })
            .catch((err) => {
              throw err;
            });
        }
      }
    })
    .catch((err) => {
      if (!err.apiErrorCode) {
        err.apiErrorCode = 1000;
      }
      next(err);
    });
};
