/****************
Generated by NODEBOOTSTRAPPER
Author: Ashutosh Kapoor
GIT LINK : https://github.com/ashu-kapoor/NODEBOOTSTRAPPER
****************/
const Opportunity = require("../models/Opportunity");
const Product = require("../models/Product");
/**
 * @param {object} req - req object
 * @param {object} res - res object
 * @param {object} next - next object
 **/

module.exports.deleteProductController = (req, res, next) => {
  const productId = req.params.productId;
  Product.findById(productId)
    .then((product) => {
      if (!product) {
        const error = new Error();
        error.apiErrorCode = 7000;
        throw error;
      } else {
        //if user exists check it doesnt exist anywhere before deleting
        checkProductExists(product)
          .then((data) => {
            if (data) {
              //user is referenced
              const error = new Error();
              error.apiErrorCode = 1000;
              error.apiData = "Product is sold";
              throw error;
            } else {
              //user is not referenced
              product
                .delete()
                .then(() => {
                  res.status(204).send();
                })
                .catch((err) => {
                  throw err;
                });
            }
          })
          .catch((err) => {
            throw err;
          });
      }
    })
    .catch((err) => {
      if (!err.apiErrorCode) {
        err.apiErrorCode = 1000;
      }
      next(err);
    });
};

const checkProductExists = async function (product) {
  //Check user exists in Opty, Case, Contact if so resolev with true else false
  const optyCount = await Opportunity.countDocuments({ products: product._id });

  if (optyCount > 0) {
    return true;
  }
  return false;
};
