/****************
Generated by NODEBOOTSTRAPPER
Author: Ashutosh Kapoor
GIT LINK : https://github.com/ashu-kapoor/NODEBOOTSTRAPPER
****************/
const Contact = require("../models/Contact");
const removeStorageFile = require("../utils/removeStorageFile");

/**
 * @param {object} req - req object
 * @param {object} res - res object
 * @param {object} next - next object
 **/

module.exports.deleteAttachmentController = (req, res, next) => {
  const contactId = req.params.contactId;
  const attachmentId = req.params.attachmentId;

  const dbRequest = Contact.findOneAndUpdate(
    {
      _id: contactId,
      "attachments.path": { $regex: ".*" + attachmentId + ".*" },
    },
    {
      $pull: {
        attachments: {
          path: { $regex: ".*" + attachmentId + ".*" },
        },
      },
    }
  )
    .then((data) => {
      if (!data) {
        const error = new Error();
        error.apiErrorCode = 7000;
        throw error;
      } else {
        //if data found but no attachment then throw error
        const attachment = data.attachments.filter((item) => {
          if (item.path.indexOf(attachmentId) >= 0) {
            return item;
          }
        });

        if (!attachment || attachment.length < 1) {
          const error = new Error();
          error.apiErrorCode = 7000;
          throw error;
        } else {
          removeStorageFile(attachment[0].path);
          res.status(204).send();
        }
      }
    })
    .catch((err) => {
      if (!err.apiErrorCode) {
        err.apiErrorCode = 1000;
      }
      next(err);
    });
};
