/****************
Generated by NODEBOOTSTRAPPER
Author: Ashutosh Kapoor
GIT LINK : https://github.com/ashu-kapoor/NODEBOOTSTRAPPER
****************/
const Case = require("../models/Case");
const mongoose = require("mongoose");

/**
 * @param {object} req - req object
 * @param {object} res - res object
 * @param {object} next - next object
 **/

module.exports.deleteCaseController = (req, res, next) => {
  const contactId = req.params.contactId;
  const caseId = req.params.caseId;
  Case.findOne({ _id: caseId, customer: contactId })
    .then((result) => {
      if (result) {
        Case.findByIdAndRemove(result._id)
          .then(() => {
            res.status(204).send();
          })
          .catch((err) => {
            const error = new Error();
            error.apiErrorCode = 1000;
          });
      } else {
        const error = new Error();
        error.apiErrorCode = 7000;
      }
    })
    .catch((err) => {
      if (!err.apiErrorCode) {
        err.apiErrorCode = 1000;
      }
      next(err);
    });
};
