/****************
Generated by NODEBOOTSTRAPPER
Author: Ashutosh Kapoor
GIT LINK : https://github.com/ashu-kapoor/NODEBOOTSTRAPPER
****************/
const Case = require("../models/Case");
/**
 * @param {object} req - req object
 * @param {object} res - res object
 * @param {object} next - next object
 **/

module.exports.getAllCasesController = (req, res, next) => {
  Case.find()
    .then((data) => {
      res.status(200).json({ cases: data });
    })
    .catch((err) => {
      const customError = new Error();
      customError.apiErrorCode = 1000;
      next(customError);
    });
};
