/****************
Generated by NODEBOOTSTRAPPER
Author: Ashutosh Kapoor
GIT LINK : https://github.com/ashu-kapoor/NODEBOOTSTRAPPER
****************/
const Contact = require("../models/Contact");
const path = require("path");
const fs = require("fs");
/**
 * @param {object} req - req object
 * @param {object} res - res object
 * @param {object} next - next object
 **/

module.exports.getAttachmentController = (req, res, next) => {
  const contactId = req.params.contactId;
  const attachmentId = req.params.attachmentId;

  const dbRequest = Contact.findOne(
    {
      _id: contactId,
      "attachments.path": { $regex: ".*" + attachmentId + ".*" },
    },
    { "attachments.$": 1 }
  )
    .then((data) => {
      if (!data) {
        const error = new Error();
        error.apiErrorCode = 7000;
        throw error;
      } else {
        //if data found but no attachment then throw error
        const filepath = data.attachments[0].path;
        const file = fs.createReadStream(path.join(__dirname, "..", filepath));
        res.setHeader("Content-Type", "text/plain");
        res.setHeader(
          "Content-Disposition",
          "inline; filename=" + filepath.split("_")[1]
        );
        res.status(200);
        file.pipe(res);
      }
    })
    .catch((err) => {
      if (!err.apiErrorCode) {
        err.apiErrorCode = 1000;
      }
      next(err);
    });
};
