/****************
Generated by NODEBOOTSTRAPPER
Author: Ashutosh Kapoor
GIT LINK : https://github.com/ashu-kapoor/NODEBOOTSTRAPPER
****************/
const Case = require("../models/Case");
/**
 * @param {object} req - req object
 * @param {object} res - res object
 * @param {object} next - next object
 **/

module.exports.getCaseController = (req, res, next) => {
  const contactId = req.params.contactId;
  const caseId = req.params.caseId;

  Case.find({ customer: contactId, _id: caseId })
    .then((cases) => {
      if (!cases || cases.length <= 0) {
        const customError = new Error();
        customError.apiErrorCode = 7000;
        throw customError;
      }
      res.status(200).json({ cases });
    })
    .catch((err) => {
      if (!err.apiErrorCode) {
        err.apiErrorCode = 1000;
      }
      next(err);
    });
};
