/****************
Generated by NODEBOOTSTRAPPER
Author: Ashutosh Kapoor
GIT LINK : https://github.com/ashu-kapoor/NODEBOOTSTRAPPER
****************/
const Contact = require("../models/Contact");
/**
 * @param {object} req - req object
 * @param {object} res - res object
 * @param {object} next - next object
 **/

module.exports.getContactController = (req, res, next) => {
  const contactId = req.params.contactId;

  Contact.findById(contactId)
    .then((contact) => {
      if (!contact) {
        const customError = new Error();
        customError.apiErrorCode = 7000;
        throw customError;
      }
      res.status(200).json({ contacts: [contact] });
    })
    .catch((err) => {
      if (!err.apiErrorCode) {
        err.apiErrorCode = 1000;
      }
      next(err);
    });
};
