/****************
Generated by NODEBOOTSTRAPPER
Author: Ashutosh Kapoor
GIT LINK : https://github.com/ashu-kapoor/NODEBOOTSTRAPPER
****************/
const Opportunity = require("../models/Opportunity");
/**
 * @param {object} req - req object
 * @param {object} res - res object
 * @param {object} next - next object
 **/

module.exports.getOpportunitiesController = (req, res, next) => {
  const contactId = req.params.contactId;

  Opportunity.find({ customer: contactId })
    .then((opties) => {
      if (!opties || opties.length <= 0) {
        const customError = new Error();
        customError.apiErrorCode = 7000;
        throw customError;
      }
      res.status(200).json({ opportunities: opties });
    })
    .catch((err) => {
      if (!err.apiErrorCode) {
        err.apiErrorCode = 1000;
      }
      next(err);
    });
};
