/****************
Generated by NODEBOOTSTRAPPER
Author: Ashutosh Kapoor
GIT LINK : https://github.com/ashu-kapoor/NODEBOOTSTRAPPER
****************/
const Product = require("../models/Product");
/**
 * @param {object} req - req object
 * @param {object} res - res object
 * @param {object} next - next object
 **/

module.exports.getProductsController = (req, res, next) => {
  Product.find()
    .then((data) => {
      const products = [];
      if (data) {
        for (const product of data) {
          const { _id, name, code } = product;
          products.push({
            _id,
            name,
            code,
            listPrice: product.listPrice.toString(),
          });
        }
      }

      res.status(200).json({ products });
    })
    .catch((err) => {
      const customError = new Error();
      customError.apiErrorCode = 1000;
      next(customError);
    });
};
