/****************
Generated by NODEBOOTSTRAPPER
Author: Ashutosh Kapoor
GIT LINK : https://github.com/ashu-kapoor/NODEBOOTSTRAPPER
****************/
const Product = require("../models/Product");
/**
 * @param {object} req - req object
 * @param {object} res - res object
 * @param {object} next - next object
 **/

module.exports.getProductController = (req, res, next) => {
  const productId = req.params.productId;

  Product.findById(productId)
    .then((product) => {
      if (!product) {
        const customError = new Error();
        customError.apiErrorCode = 7000;
        throw customError;
      }
      const { _id, name, code } = product;
      res
        .status(200)
        .json({
          products: [
            { _id, name, code, listPrice: product.listPrice.toString() },
          ],
        });
    })
    .catch((err) => {
      if (!err.apiErrorCode) {
        err.apiErrorCode = 1000;
      }
      next(err);
    });
};
