/****************
Generated by NODEBOOTSTRAPPER
Author: Ashutosh Kapoor
GIT LINK : https://github.com/ashu-kapoor/NODEBOOTSTRAPPER
****************/

const User = require("../models/User");

/**
 * @param {object} req - req object
 * @param {object} res - res object
 * @param {object} next - next object
 **/

module.exports.getUsersController = (req, res, next) => {
  User.find({}, "-password")
    .then((data) => {
      res.status(200).json({ users: data });
    })
    .catch((err) => {
      const customError = new Error();
      customError.apiErrorCode = 1000;
      next(customError);
    });
};
