/****************
Generated by NODEBOOTSTRAPPER
Author: Ashutosh Kapoor
GIT LINK : https://github.com/ashu-kapoor/NODEBOOTSTRAPPER
****************/

const User = require("../models/User");

/**
 * @param {object} req - req object
 * @param {object} res - res object
 * @param {object} next - next object
 **/

module.exports.getUserController = (req, res, next) => {
  const userId = req.params.userId;

  User.findById(userId, "-password")
    .then((user) => {
      if (!user) {
        const customError = new Error();
        customError.apiErrorCode = 7000;
        throw customError;
      }
      res.status(200).json({ users: [user] });
    })
    .catch((err) => {
      if (!err.apiErrorCode) {
        err.apiErrorCode = 1000;
      }
      next(err);
    });
};
