/****************
Generated by NODEBOOTSTRAPPER
Author: Ashutosh Kapoor
GIT LINK : https://github.com/ashu-kapoor/NODEBOOTSTRAPPER
****************/
const Case = require("../models/Case");
/**
 * @param {object} req - req object
 * @param {object} res - res object
 * @param {object} next - next object
 **/

module.exports.updateCaseController = (req, res, next) => {
  const contactId = req.params.contactId;
  const caseId = req.params.caseId;

  const dbRequest = {
    caseNumber: req.body.caseNumber,
    description: req.body.description,
    stage: req.body.stage,
    priority: req.body.priority,
    customer: contactId,
  };

  Case.findOneAndUpdate({ _id: caseId, owner: contactId }, dbRequest)
    .then((data) => {
      if (!data) {
        const error = new Error();
        error.apiErrorCode = 7000;
        throw error;
      }
      res.status(204).send();
    })
    .catch((err) => {
      if (!err.apiErrorCode) {
        err.apiErrorCode = 1000;
      }
      next(err);
    });
};
