/****************
Generated by NODEBOOTSTRAPPER
Author: Ashutosh Kapoor
GIT LINK : https://github.com/ashu-kapoor/NODEBOOTSTRAPPER
****************/
const User = require("../models/User");
/**
 * @param {object} req - req object
 * @param {object} res - res object
 * @param {object} next - next object
 **/

module.exports.updateUserController = (req, res, next) => {
  const username = req.body.username;
  const password = req.body.password;
  const role = req.body.role;
  const email = req.body.email;
  const userId = req.params.userId;

  bcrypt
    .hash(password, process.env.passwordSalt)
    .then((hashPass) => {
      User.findOneAndUpdate(
        { _id: userId },
        { username, password, role, email }
      )
        .then((data) => {
          if (!data) {
            const error = new Error();
            error.apiErrorCode = 7000;
            throw error;
          }
          res.status(204).send();
        })
        .catch((err) => {
          throw err;
        });
    })
    .catch((err) => {
      if (!err.apiErrorCode) {
        err.apiErrorCode = 1000;
      }
      next(err);
    });
};
