/****************
Generated by NODEBOOTSTRAPPER
Author: Ashutosh Kapoor
GIT LINK : https://github.com/ashu-kapoor/NODEBOOTSTRAPPER
****************/
const Opportunity = require("../models/Opportunity");
/**
 * @param {object} req - req object
 * @param {object} res - res object
 * @param {object} next - next object
 **/

module.exports.updateOpportunityController = (req, res, next) => {
  const contactId = req.params.contactId;
  const opportunityId = req.params.opportunityId;

  const dbRequest = {
    name: req.body.name,
    stage: req.body.stage,
    products: req.body.products,
    closeDate: req.body.closeDate,
    customer: contactId,
  };

  Opportunity.findOneAndUpdate(
    { _id: opportunityId, owner: contactId },
    dbRequest
  )
    .then((data) => {
      if (!data) {
        const error = new Error();
        error.apiErrorCode = 7000;
        throw error;
      }
      res.status(204).send();
    })
    .catch((err) => {
      if (!err.apiErrorCode) {
        err.apiErrorCode = 1000;
      }
      next(err);
    });
};
