/****************
Generated by NODEBOOTSTRAPPER
Author: Ashutosh Kapoor
GIT LINK : https://github.com/ashu-kapoor/NODEBOOTSTRAPPER
****************/
const Product = require("../models/Product");

/**
 * @param {object} req - req object
 * @param {object} res - res object
 * @param {object} next - next object
 **/

module.exports.updateProductController = (req, res, next) => {
  const name = req.body.name;
  const code = req.body.code;
  const listPrice = req.body.listPrice;
  const productId = req.params.productId;

  Product.findOneAndUpdate({ _id: productId }, { name, code, listPrice })
    .then((data) => {
      if (!data) {
        const error = new Error();
        error.apiErrorCode = 7000;
        throw error;
      }
      res.status(204).send();
    })
    .catch((err) => {
      if (!err.apiErrorCode) {
        err.apiErrorCode = 1000;
      }
      next(err);
    });
};
